config/routes.rb
Rails.application.routes.draw do
  root 'application#index'
  mount ActionCable.server => "/cable"
  scope :users do
    get 'signin', to: 'users#signin_view', as: :signin_view
    post 'signin', to: 'users#signin', as: :signin_api

    get 'signup', to: 'users#signup_view', as: :signup_view
    post 'signup', to: 'users#signup', as: :signup_api

    get 'account', to: 'users#account', as: :account
    post 'signout', to: 'users#signout', as: :signout
  end

  post 'orders/send_message', to: 'orders#send_message', as: :send_message
  resources :orders, only: [:index, :show, :new, :create, :edit, :update]
end

app/models/user.rb
class User < ApplicationRecord
  validates :email, :address, :first_name, :phone_number, presence: true, length: { minimum: 4, maximum: 254 }
  validates :last_name, length: { maximum: 254 }, if: :last_name
  validates :phone_number, format: { with: P_NUMBER_REGEXP }
  validates :email, format: { with: EMAIL_REGEXP }, uniqueness: { case_sensitive: false }
  validates :password, length: { minimum: 8, maximum: 254 }, if: :password

  has_one :membership, dependent: :destroy
  has_many :orders, dependent: :destroy

  after_create :create_membership_custom
  has_secure_password

  private

  def create_membership_custom
    unless self.create_membership member_type: 'normal'
      errors.add :membership, 'No se pudo validar la información de pago'
      raise ActiveRecord::Rollback
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_logged_in, only: %i[account signout]
  before_action :require_unlogged_in, except: %i[account signout]

  def account
  end

  def signup
    user_p = user_params[:user]

    user_p[:password_confirmation] = user_p[:password]

    @user = User.new user_p
    render :signup and return unless @user.valid?
    unless @user.save
      gon.push notice: 'Error al crear la cuenta'
      render :signup and return
    end
    gon.push notice: 'Cuenta creada correctamente'
    session[:user_id] = @user.id
    redirect_to root_path
  end

  def signup_view
    @user = User.new
    render :signup
  end

  def signin
    auth_p   = auth_params
    email    = auth_p[:user][:email]
    password = auth_p[:user][:password]
    @user    = User.find_by email: email
    if @user.nil? or not (@user.authenticate password)
      gon.push notice: 'Usuario o contraseña errados'
      @user = User.new auth_p[:user]
      render :signin and return
    end
    gon.push notice: 'Sesión iniciada correctamente'
    session[:user_id] = @user.id
    redirect_to root_path
  end

  def signin_view
    @user = User.new
    render :signin
  end

  def signout
    session.delete :user_id
    redirect_to root_path
  end

  private

  def user_params
    params.permit(user: %i[email password first_name last_name phone_number address])
  end

  def auth_params
    params.permit(user: %i[email password])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/account.html.erb
<div id="account">
  <div id="account__inner">
    <%= link_to signout_path, method: :post, class: 'mdc-button mdc-button--raised mdc-top-app-bar__action-item', data: { 'mdc-auto-init': 'MDCRipple' } do %>
      <span class="mdc-button__ripple"></span>
      <span class="mdc-button__label">cerrar sesión</span>
    <% end %>
  </div>
</div>

<%= stylesheet_link_tag 'users' %>

app/views/users/login.html.erb
<div id="login">
  <div id="login__blur"></div>
  <div class="mdc-layout-grid" id="login__form">
    <div class="mdc-layout-grid__inner">
      <div class="mdc-layout-grid__cell--span-3"></div>
      <div class="mdc-layout-grid__cell--span-6">
        <%= form_with scope: :user, url: signin_path, class: 'mdc-card', method: :post do |f| %>
          <h5 class="mdc-typography--headline5 secondary-typography">Iniciar sesión</h5>
          <br>
          <div class="mdc-text-field mdc-text-field--outlined mdc-text-field--with-leading-icon" data-mdc-auto-init="MDCTextField">
            <i class="material-icons mdc-text-field__icon">account_circle</i>
            <%= f.text_field :email, class: 'mdc-text-field__input', id: 'email', type: 'email' %>
            <div class="mdc-notched-outline">
              <div class="mdc-notched-outline__leading"></div>
              <div class="mdc-notched-outline__notch">
                <label for="email" class="mdc-floating-label">Correo electrónico</label>
              </div>
              <div class="mdc-notched-outline__trailing"></div>
            </div>
          </div>
          <div class="mdc-text-field mdc-text-field--outlined mdc-text-field--with-leading-icon" data-mdc-auto-init="MDCTextField">
            <i class="material-icons mdc-text-field__icon">lock</i>
            <%= f.text_field :password, class: 'mdc-text-field__input', id: 'password', type: 'password' %>
            <div class="mdc-notched-outline">
              <div class="mdc-notched-outline__leading"></div>
              <div class="mdc-notched-outline__notch">
                <label for="password" class="mdc-floating-label">Contraseña</label>
              </div>
              <div class="mdc-notched-outline__trailing"></div>
            </div>
          </div>
          <br>
          <%= f.submit 'continuar', class: 'mdc-button mdc-button--raised', data: { 'mdc-auto-init': 'MDCRipple' } do %>
            <span class="mdc-button__ripple"></span>
          <% end %>
          <%= link_to new_user_path, class: 'mdc-button mdc-button--outlined mdc-theme--on-primary', data: { 'mdc-auto-init': 'MDCRipple' } do %>
            <span class="mdc-button__ripple"></span>
            <span class="mdc-button__label">registrarse</span>
          <% end %>
        <% end %>
      </div>
      <div class="mdc-layout-grid__cell--span-3"></div>
    </div>
  </div>
</div>

<%= stylesheet_link_tag 'users' %>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/signin.html.erb
<div id="signin">
  <div id="signin__blur">
  <div class="mdc-layout-grid" id="signin__form">
    <div class="mdc-layout-grid__inner">
      <div class="mdc-layout-grid__cell--span-3-desktop mdc-layout-grid__cell--span-2-tablet"></div>
      <div class="mdc-layout-grid__cell--span-6-desktop mdc-layout-grid__cell--span-4-tablet mdc-layout-grid__cell--span-4-phone">
        <%= form_with model: @user, url: signin_api_path, class: 'mdc-card', method: :post, local: true do |f| %>
          <h5 class="mdc-typography--headline5 secondary-typography">Iniciar sesión</h5>
          <br>
          <div class="mdc-text-field mdc-text-field--outlined mdc-text-field--with-leading-icon" data-mdc-auto-init="MDCTextField">
            <i class="material-icons mdc-text-field__icon">alternate_email</i>
            <%= f.text_field :email, class: 'mdc-text-field__input', id: 'email', type: 'email' %>
            <div class="mdc-notched-outline">
              <div class="mdc-notched-outline__leading"></div>
              <div class="mdc-notched-outline__notch">
                <label for="email" class="mdc-floating-label">Correo electrónico</label>
              </div>
              <div class="mdc-notched-outline__trailing"></div>
            </div>
          </div>
          <div class="mdc-text-field mdc-text-field--outlined mdc-text-field--with-leading-icon" data-mdc-auto-init="MDCTextField">
            <i class="material-icons mdc-text-field__icon">lock</i>
            <%= f.text_field :password, class: 'mdc-text-field__input', id: 'password', type: 'password' %>
            <div class="mdc-notched-outline">
              <div class="mdc-notched-outline__leading"></div>
              <div class="mdc-notched-outline__notch">
                <label for="password" class="mdc-floating-label">Contraseña</label>
              </div>
              <div class="mdc-notched-outline__trailing"></div>
            </div>
          </div>
          <br>
          <%= f.submit 'continuar', class: 'mdc-button mdc-button--raised', data: { 'mdc-auto-init': 'MDCRipple' } do %>
            <span class="mdc-button__ripple"></span>
          <% end %>
          <%= link_to signup_view_path, class: 'mdc-button mdc-button--outlined mdc-theme--on-primary', data: { 'mdc-auto-init': 'MDCRipple' } do %>
            <span class="mdc-button__ripple"></span>
            <span class="mdc-button__label">registrarse</span>
          <% end %>
        <% end %>
      </div>
      <div class="mdc-layout-grid__cell--span-3-desktop mdc-layout-grid__cell--span-2-tablet"></div>
    </div>
  </div>
</div>
</div>

<%= stylesheet_link_tag 'users' %>

app/views/users/signup.html.erb
<div id="signup">
  <div id="signup__blur">
    <div class="mdc-layout-grid" id="signup__form">
      <div class="mdc-layout-grid__inner">
        <div class="mdc-layout-grid__cell--span-2-desktop mdc-layout-grid__cell--span-1-tablet"></div>
        <div class="mdc-layout-grid__cell--span-8-desktop mdc-layout-grid__cell--span-6-tablet mdc-layout-grid__cell--span-4-phone">
          <%= form_with model: @user, url: signup_api_path, class: 'mdc-card', method: :post, local: true do |f| %>
            <h5 class="mdc-typography--headline5 secondary-typography">Crear cuenta</h5>
            <br>
            <div class="mdc-layout-grid__inner">
              <div class="mdc-layout-grid__cell--span-6-desktop mdc-layout-grid__cell--span-8-tablet mdc-layout-grid__cell--span-4-phone">
                <div class="mdc-text-field mdc-text-field--outlined<%= @user.errors.messages[:first_name].empty? ? '' : ' mdc-text-field--invalid' %>" data-mdc-auto-init="MDCTextField">
                  <%= f.text_field :first_name, class: 'mdc-text-field__input', id: 'first_name', type: 'text' %>
                  <div class="mdc-notched-outline">
                    <div class="mdc-notched-outline__leading"></div>
                    <div class="mdc-notched-outline__notch">
                      <label for="first_name" class="mdc-floating-label">Nombres</label>
                    </div>
                    <div class="mdc-notched-outline__trailing"></div>
                  </div>
                </div>
                <div class="mdc-text-field-helper-line">
                  <div class="mdc-text-field-helper-text mdc-text-field-helper-text--validation-msg" aria-hidden="true">
                    <%= @user.errors.messages[:first_name].first %>
                  </div>
                </div>
              </div>
              <div class="mdc-layout-grid__cell--span-6-desktop mdc-layout-grid__cell--span-8-tablet mdc-layout-grid__cell--span-4-phone">
                <div class="mdc-text-field mdc-text-field--outlined<%= @user.errors.messages[:last_name].empty? ? '' : ' mdc-text-field--invalid' %>" data-mdc-auto-init="MDCTextField">
                  <%= f.text_field :last_name, class: 'mdc-text-field__input', id: 'last_name', type: 'text' %>
                  <div class="mdc-notched-outline">
                    <div class="mdc-notched-outline__leading"></div>
                    <div class="mdc-notched-outline__notch">
                      <label for="last_name" class="mdc-floating-label">Apellidos</label>
                    </div>
                    <div class="mdc-notched-outline__trailing"></div>
                  </div>
                </div>
                <div class="mdc-text-field-helper-line">
                  <div class="mdc-text-field-helper-text mdc-text-field-helper-text--validation-msg" aria-hidden="true">
                    <%= @user.errors.messages[:last_name].first %>
                  </div>
                </div>
              </div>
              <div class="mdc-layout-grid__cell--span-7-desktop mdc-layout-grid__cell--span-8-tablet mdc-layout-grid__cell--span-4-phone">
                <div class="mdc-text-field mdc-text-field--outlined mdc-text-field--with-leading-icon<%= @user.errors.messages[:email].empty? ? '' : ' mdc-text-field--invalid' %>" data-mdc-auto-init="MDCTextField">
                  <i class="material-icons mdc-text-field__icon">alternate_email</i>
                  <%= f.text_field :email, class: 'mdc-text-field__input', id: 'email', type: 'email' %>
                  <div class="mdc-notched-outline">
                    <div class="mdc-notched-outline__leading"></div>
                    <div class="mdc-notched-outline__notch">
                      <label for="email" class="mdc-floating-label">Correo electrónico</label>
                    </div>
                    <div class="mdc-notched-outline__trailing"></div>
                  </div>
                </div>
                <div class="mdc-text-field-helper-line">
                  <div class="mdc-text-field-helper-text mdc-text-field-helper-text--validation-msg" aria-hidden="true">
                    <%= @user.errors.messages[:email].first %>
                  </div>
                </div>
              </div>
              <div class="mdc-layout-grid__cell--span-5-desktop mdc-layout-grid__cell--span-8-tablet mdc-layout-grid__cell--span-4-phone">
                <div class="mdc-text-field mdc-text-field--outlined mdc-text-field--with-leading-icon<%= @user.errors.messages[:password].empty? ? '' : ' mdc-text-field--invalid' %>" data-mdc-auto-init="MDCTextField">
                  <i class="material-icons mdc-text-field__icon">lock</i>
                  <%= f.text_field :password, class: 'mdc-text-field__input', id: 'password', type: 'password' %>
                  <div class="mdc-notched-outline">
                    <div class="mdc-notched-outline__leading"></div>
                    <div class="mdc-notched-outline__notch">
                      <label for="password" class="mdc-floating-label">Contraseña</label>
                    </div>
                    <div class="mdc-notched-outline__trailing"></div>
                  </div>
                </div>
                <div class="mdc-text-field-helper-line">
                  <div class="mdc-text-field-helper-text mdc-text-field-helper-text--validation-msg" aria-hidden="true">
                    <%= @user.errors.messages[:password].first %>
                  </div>
                </div>
              </div>
              <div class="mdc-layout-grid__cell--span-7-desktop mdc-layout-grid__cell--span-8-tablet mdc-layout-grid__cell--span-4-phone">
                <div class="mdc-text-field mdc-text-field--outlined mdc-text-field--with-leading-icon<%= @user.errors.messages[:address].empty? ? '' : ' mdc-text-field--invalid' %>" data-mdc-auto-init="MDCTextField">
                  <i class="material-icons mdc-text-field__icon">home</i>
                  <%= f.text_field :address, class: 'mdc-text-field__input', id: 'address', type: 'text' %>
                  <div class="mdc-notched-outline">
                    <div class="mdc-notched-outline__leading"></div>
                    <div class="mdc-notched-outline__notch">
                      <label for="address" class="mdc-floating-label">Dirección (sólo Barranquilla)</label>
                    </div>
                    <div class="mdc-notched-outline__trailing"></div>
                  </div>
                </div>
                <div class="mdc-text-field-helper-line">
                  <div class="mdc-text-field-helper-text mdc-text-field-helper-text--validation-msg" aria-hidden="true">
                    <%= @user.errors.messages[:address].first %>
                  </div>
                </div>
              </div>
              <div class="mdc-layout-grid__cell--span-5-desktop mdc-layout-grid__cell--span-8-tablet mdc-layout-grid__cell--span-4-phone">
                <div class="mdc-text-field mdc-text-field--outlined mdc-text-field--with-leading-icon<%= @user.errors.messages[:phone_number].empty? ? '' : ' mdc-text-field--invalid' %>" data-mdc-auto-init="MDCTextField">
                  <i class="material-icons mdc-text-field__icon">call</i>
                  <%= f.text_field :phone_number, class: 'mdc-text-field__input', id: 'phone_number', type: 'tel' %>
                  <div class="mdc-notched-outline">
                    <div class="mdc-notched-outline__leading"></div>
                    <div class="mdc-notched-outline__notch">
                      <label for="phone_number" class="mdc-floating-label">Telefono</label>
                    </div>
                    <div class="mdc-notched-outline__trailing"></div>
                  </div>
                </div>
                <div class="mdc-text-field-helper-line">
                  <div class="mdc-text-field-helper-text mdc-text-field-helper-text--validation-msg" aria-hidden="true">
                    <%= @user.errors.messages[:phone_number].first %>
                  </div>
                </div>
              </div>
            </div>
            <br><br>
            <h5 class="mdc-typography--headline5 secondary-typography">Datos de pago</h5>
            <br>
            <div class="mdc-layout-grid__inner">
              <div class="mdc-layout-grid__cell--span-6-desktop mdc-layout-grid__cell--span-8-tablet mdc-layout-grid__cell--span-4-phone">
                <div class="mdc-text-field mdc-text-field--outlined mdc-text-field--with-leading-icon" data-mdc-auto-init="MDCTextField">
                  <i class="material-icons mdc-text-field__icon">credit_card</i>
                  <%= f.text_field :credit_card, class: 'mdc-text-field__input', id: 'credit_card', type: 'text', maxlength: 16, minlength: 16 %>
                  <div class="mdc-notched-outline">
                    <div class="mdc-notched-outline__leading"></div>
                    <div class="mdc-notched-outline__notch">
                      <label for="credit_card" class="mdc-floating-label">Numero de tarjeta</label>
                    </div>
                    <div class="mdc-notched-outline__trailing"></div>
                  </div>
                </div>
              </div>
              <div class="mdc-layout-grid__cell--span-3-desktop mdc-layout-grid__cell--span-5-tablet mdc-layout-grid__cell--span-2-phone">
                <div class="mdc-text-field mdc-text-field--outlined mdc-text-field--with-leading-icon" data-mdc-auto-init="MDCTextField">
                  <i class="material-icons mdc-text-field__icon">lock</i>
                  <%= f.text_field :ccv, class: 'mdc-text-field__input', id: 'ccv', type: 'password', maxlength: 3 %>
                  <div class="mdc-notched-outline">
                    <div class="mdc-notched-outline__leading"></div>
                    <div class="mdc-notched-outline__notch">
                      <label for="ccv" class="mdc-floating-label">CCV</label>
                    </div>
                    <div class="mdc-notched-outline__trailing"></div>
                  </div>
                </div>
              </div>
              <div class="mdc-layout-grid__cell--span-3-desktop mdc-layout-grid__cell--span-3-tablet mdc-layout-grid__cell--span-2-phone">
                <div class="mdc-text-field mdc-text-field--outlined mdc-text-field--with-leading-icon" data-mdc-auto-init="MDCTextField">
                  <i class="material-icons mdc-text-field__icon">today</i>
                  <%= f.text_field :date, class: 'mdc-text-field__input', id: 'date', type: 'text', maxlength: 5 %>
                  <div class="mdc-notched-outline">
                    <div class="mdc-notched-outline__leading"></div>
                    <div class="mdc-notched-outline__notch">
                      <label for="date" class="mdc-floating-label">Fecha</label>
                    </div>
                    <div class="mdc-notched-outline__trailing"></div>
                  </div>
                </div>
              </div>
            </div>
            <br>
            <p class="mdc-typography--body1">Se realizará un cobro por el primer mes de suscripción de la membresía de
              <strong>iFoodX</strong> por un valor de $ 15.700 pesos colombianos. La suscripción puede ser cancelada en
              cualquier momento sin derecho a devolución alguna. <strong>iFoodX</strong> no realizará cobros
              automáticos, la suscripción se deberá pagar manualmente cada mes.</p>
            <br>
            <p class="mdc-typography--body1">Al continuar está usted aceptando todos los términos y condiciones de
              <strong>iFoodX Inc.</strong> y su política de tratamiento de información y privacidad.</p>
            <br>
            <%= f.submit 'continuar', class: 'mdc-button mdc-button--raised', data: { 'mdc-auto-init': 'MDCRipple' } do %>
              <span class="mdc-button__ripple"></span>
            <% end %>
            <%= link_to signin_view_path, class: 'mdc-button mdc-button--outlined mdc-theme--on-primary', data: { 'mdc-auto-init': 'MDCRipple' } do %>
              <span class="mdc-button__ripple"></span>
              <span class="mdc-button__label">iniciar sesión</span>
            <% end %>
          <% end %>
        </div>
        <div class="mdc-layout-grid__cell--span-2-desktop mdc-layout-grid__cell--span-1-tablet"></div>
      </div>
    </div>
  </div>
</div>
<%= stylesheet_link_tag 'users' %>