config/routes.rb
Rails.application.routes.draw do
  root 'application#index'
  mount ActionCable.server => "/cable"
  scope :users do
    get 'signin', to: 'users#signin_view', as: :signin_view
    post 'signin', to: 'users#signin', as: :signin_api

    get 'signup', to: 'users#signup_view', as: :signup_view
    post 'signup', to: 'users#signup', as: :signup_api

    get 'account', to: 'users#account', as: :account
    post 'signout', to: 'users#signout', as: :signout
  end

  post 'orders/send_message', to: 'orders#send_message', as: :send_message
  resources :orders, only: [:index, :show, :new, :create, :edit, :update]
end

app/views/layouts/_chat.html.erb
<div id="chat" class="closed shaped">
  <button onclick="toggle()" class="mdc-button mdc-button--raised" data-mdc-auto-init="MDCRipple" id="chat-opener">
    <span class="mdc-button__icon material-icons">chat</span>
    <span class="mdc-button__label">chat</span>
    <span class="mdc-button__ripple"></span>
  </button>
  <div id="chat-header">
    <h6 class="mdc-typography--headline6">Chat</h6>
  </div>
  <div id="messages">
    <% @order.messages.each do |m| %>
      <div class="<%= m.user.is_admin ? 'l-message' : 'r-message' %>">
        <p class="mdc-typography--body1"><%= m.text %></p>
      </div>
      <br>
    <% end %>
  </div>
  <%= form_with model: Message.new, url: '/orders/send_message', id: 'chat-message', method: :post, local: false do |f| %>
    <div class="mdc-text-field mdc-text-field--no-label mdc-text-field--dense mdc-text-field--outlined" data-mdc-auto-init="MDCTextField">
      <input type="hidden" name="message[order_id]" value="<%= @order.id %>">
      <%= f.text_field :text, class: 'mdc-text-field__input', id: 'text', min: 1, type: 'text' %>
      <div class="mdc-notched-outline">
        <div class="mdc-notched-outline__leading"></div>
        <div class="mdc-notched-outline__notch">
        </div>
        <div class="mdc-notched-outline__trailing"></div>
      </div>
    </div>
    <%= f.submit 'enviar', class: 'mdc-button', data: { 'mdc-auto-init': 'MDCRipple' } do %>
      <span class="mdc-button__ripple"></span>
    <% end %>
  <% end %>
</div>

app/views/layouts/_navbar.html.erb
<header class="mdc-top-app-bar mdc-top-app-bar--fixed <%= (current_page? root_path or current_page? signin_view_path or current_page? signup_view_path or current_page? account_path) ? "" : "mdc-top-app-bar--force-black" %> mdc-theme--transparent mdc-theme--on-secondary" data-mdc-auto-init="MDCTopAppBar">
  <div class="mdc-top-app-bar__row">
    <div class="mdc-top-app-bar__section mdc-top-app-bar__section--align-start">
      <span class="mdc-top-app-bar__title secondary-typography">iFoodX</span>
    </div>
    <div class="mdc-top-app-bar__section mdc-top-app-bar__section--align-end">
      <%= link_to root_path, class: 'mdc-button mdc-top-app-bar__action-item mdc-theme--on-secondary', data: { 'mdc-auto-init': 'MDCRipple' } do %>
        <span class="mdc-button__ripple"></span>
        <span class="mdc-button__label">inicio</span>
      <% end %>
      <% if logged_in? %>
        <%= link_to orders_path, class: 'mdc-button mdc-top-app-bar__action-item mdc-theme--on-secondary', data: { 'mdc-auto-init': 'MDCRipple' } do %>
          <span class="mdc-button__ripple"></span>
          <span class="mdc-button__label">pedidos</span>
        <% end %>
        <%= link_to account_path, class: 'mdc-button mdc-button--raised mdc-top-app-bar__action-item', data: { 'mdc-auto-init': 'MDCRipple' } do %>
          <span class="mdc-button__ripple"></span>
          <span class="mdc-button__label">mi cuenta</span>
        <% end %>
      <% else %>
        <%= link_to signin_view_path, class: 'mdc-button mdc-button--raised mdc-top-app-bar__action-item', data: { 'mdc-auto-init': 'MDCRipple' } do %>
          <span class="mdc-button__ripple"></span>
          <span class="mdc-button__label">acceder</span>
        <% end %>
      <% end %>
    </div>
  </div>
</header>

app/views/layouts/_notice.html.erb
<div class="mdc-snackbar" data-mdc-auto-init="MDCSnackbar" id="notice">
  <div class="mdc-snackbar__surface">
    <div class="mdc-snackbar__label" role="status" aria-live="polite">Can't send photo. Retry in 5 seconds.</div>
    <div class="mdc-snackbar__actions">
      <button class="mdc-icon-button mdc-snackbar__dismiss material-icons" title="Dismiss">close</button>
    </div>
  </div>
</div>

app/views/layouts/_p1.html.erb
<% unless admin %>
  <%= link_to new_order_path, class: 'mdc-button mdc-button--raised mdc-top-app-bar__action-item', id: 'new-order-btn', data: { 'mdc-auto-init': 'MDCRipple' } do %>
    <span class="mdc-button__ripple"></span>
    <span class="mdc-button__label">nueva orden</span>
  <% end %>
<% end %>
<div class="mdc-layout-grid" id="orders">
  <div class="mdc-layout-grid__inner">
    <div class="mdc-layout-grid__cell--span-12">
      <% if @orders.any? %>
        <h5 class="mdc-typography--headline5 secondary-typography">Pedidos</h5>
        <ul class="mdc-list mdc-list--two-line">
          <% @orders.each do |o| %>
            <%= link_to admin ? edit_order_path(o) : order_path(o), class: 'mdc-list-item' do %>
            <span class="mdc-list-item__text">
              <span class="mdc-list-item__primary-text"><%= o.created_at.strftime("%B %d, %Y - %l:%M %p") %></span>
              <span class="mdc-list-item__secondary-text">Ingredients: <%= o.ingredients.size %>
                · Total: $ <%= o.price %> · Estado: <strong class="text-state-<%= Order.states[o.state] %>"><em><%= o.state %></em></strong></span>
            </span>
            <% end %>
          <% end %>
        </ul>
      <% else %>
        <h5 class="mdc-typography--headline5 secondary-typography">No has hecho ningun pedido aun</h5>
      <% end %>
    </div>
  </div>
</div>

<%= stylesheet_link_tag 'orders' %>

app/views/layouts/_p2.html.erb
<div class="mdc-layout-grid" id="orders">
  <div class="mdc-layout-grid__inner">
    <div class="mdc-layout-grid__cell--span-6-desktop mdc-layout-grid__cell--span-4-tablet mdc-layout-grid__cell--span-4-phone">
      <h5 class="mdc-typography--headline5 secondary-typography">Estado: <em><strong><%= @order.state %></strong></em>
      </h5>
      <h5 class="mdc-typography--headline5 secondary-typography">Precio: <strong>$ <%= @order.price %></strong>
      </h5>
      <h5 class="mdc-typography--headline5 secondary-typography">Preparación</h5>
      <p class="mdc-typography--body1"><%= @order.preparation %></p>
    </div>
    <div class="mdc-layout-grid__cell--span-6 mdc-layout-grid__cell--span-4-tablet mdc-layout-grid__cell--span-4-phone">
      <h5 class="mdc-typography--headline5 secondary-typography">Ingredientes</h5>
      <ul class="mdc-list mdc-list--two-line">
        <% @order.order_ingredients.each do |i| %>
          <li class="mdc-list-item">
            <span class="mdc-list-item__text">
              <span class="mdc-list-item__primary-text"><%= i.ingredient.name %></span>
              <span class="mdc-list-item__secondary-text">Cantidad: <%= i.amount %>
                · $ <%= i.ingredient.price * i.amount %></span>
            </span>
          </li>
        <% end %>
      </ul>
    </div>
    <%= render partial: 'layouts/chat' %>
  </div>
</div>

<%= stylesheet_link_tag 'orders' %>

<script>
    function toggle() {
        const el = document.getElementById("chat")
        if (el.className.includes("closed")) {
            el.className = "opened shaped"
        } else {
            el.className = "closed shaped"
        }
    }
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="es">
<head>
  <title>iFoodX</title>
  <%= action_cable_meta_tag %>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= Gon::Base.render_data %>
  <!--    <link href="https://fonts.googleapis.com/css?family=Roboto:300,300i,400,400i,500,500i,700,700i|Roboto+Slab:300,400,700" rel="stylesheet">-->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:500|Rubik:500">
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<%= render partial: 'layouts/navbar' %>
<%= render partial: 'layouts/notice' %>
<%= yield %>
<%= javascript_pack_tag 'mdc_auto_init', 'data-turbolinks-track': 'reload' %>
</body>
</html>